### PR TITLE
Add opt-out for umami tracking

### PR DESCRIPTION
**Pull request by benjaminrsherman**
Consolidates all tracking into two functions in `utilities.ts`.  In addition to letting us do global disables of tracking like this, it should make switching to a different backend simpler should we decide to do that.  As it stands now, the functions just abort if umami tracking has been opted-out from.

Tracking defaults to opt-in since it's already anonymized, so opting out should (hopefully) only be done by the super privacy conscious.  I'm not sure if different phrasings of the setting will affect how many people opt-out.

@johnnyapol has been added as a reviewer since they have expressed interest in this feature.  Please let me know if you have any feedback.

Resolves issue #268.

### CODE REVIEW

**Comment by elihschiff** [comment]
Why not just update umami and use the built in feature to disable tracking? https://github.com/mikecao/umami/releases/tag/v1.4.0

**Comment by benjaminrsherman** [comment]
> Why not just update umami and use the built in feature to disable tracking? https://github.com/mikecao/umami/releases/tag/v1.4.0

I didn't know about that feature, but I still think this is a good change since it lets us change analytics backends without needing to modify localstorage or internal API usages.  At the very least, moving all code which handles the Umami API to `utilities.ts` is a good thing just because it means we don't need all of the weird Umami imports and expected errors wherever Umami is used.

**Review by elihschiff — APPROVED** [review]
Ok I agree, this could be helpful if we in the future want to switch platforms.
Code looks fine to me

**Comment by johnnyapol** [comment]
FWIW I never had serious concerns over the analytics but the choice to opt out is always a good thing. Plus, it could help in the future for things like GDPR compliance.

**Review by johnnyapol — APPROVED** [review]

**Comment by elihschiff** [comment]
@benjaminrsherman  Can you fix the merge conflicts? In theory I think you just have to move your changes to the site folder

**Pull request merged**
